"""Locale label dicts resolved into body placeholders."""
from _build.facts import facts_placeholders
from _build.generators.dpwh import _build_dpwh_labels
from _build.locales import t
from _build.templates import fill


def resolve_body_placeholders(body: str, locale: dict, asset_base: str) -> str:
    """Resolve all locale placeholders in page body content."""
    return fill(body, {
        "ASSET_BASE": asset_base,
        **facts_placeholders(),
        ** _build_page_body_labels(locale),
        ** _build_homepage_labels(locale),
        ** _build_statistics_labels(locale),
        ** _build_transparency_labels(locale),
        ** _build_search_labels(locale),
    })

def _build_page_body_labels(locale: dict) -> dict:
    return {
        "ABOUT_CONTRIBUTE_CODE": t(locale, "about.contribute_code", ""),
        "ABOUT_CONTRIBUTE_GET_INVOLVED": t(locale, "about.contribute_get_involved", ""),
        "ABOUT_CONTRIBUTE_REPORT": t(locale, "about.contribute_report", ""),
        "ABOUT_CONTRIBUTE_SHARE": t(locale, "about.contribute_share", ""),
        "ABOUT_CONTRIBUTE_VERIFY": t(locale, "about.contribute_verify", ""),
        "ABOUT_DISCLAIMER_NOTICE": t(locale, "about.disclaimer_notice", ""),
        "ABOUT_GEOGRAPHY": t(locale, "about.geography", ""),
        "ABOUT_HISTORY": t(locale, "about.history", ""),
        "ABOUT_HISTORY_ERA1": t(locale, "about.history_era1", ""),
        "ABOUT_HISTORY_ERA2": t(locale, "about.history_era2", ""),
        "ABOUT_HISTORY_ERA3": t(locale, "about.history_era3", ""),
        "ABOUT_HISTORY_ERA5": t(locale, "about.history_era5", ""),
        "ABOUT_HISTORY_TITLE": t(locale, "about.history_title", ""),
        "ABOUT_MUNICIPALITY_TITLE": t(locale, "about.municipality_title", ""),
        "ABOUT_PHOTO_BRIDGE": t(locale, "about.photo_bridge", ""),
        "ABOUT_PHOTO_MARKET": t(locale, "about.photo_market", ""),
        "ABOUT_PHOTO_OFFICIALS": t(locale, "about.photo_officials", ""),
        "ABOUT_PHOTO_PLAZA": t(locale, "about.photo_plaza", ""),
        "ABOUT_PHOTO_SCHOOL": t(locale, "about.photo_school", ""),
        "ABOUT_POPULATION_GROWTH": t(locale, "about.population_growth", ""),
        "ABOUT_POPULATION_SUBTITLE": t(locale, "about.population_subtitle", ""),
        "ABOUT_PROJECT_HOW": t(locale, "about.project_how", ""),
        "ABOUT_PROJECT_MISSION": t(locale, "about.project_mission", ""),
        "ABOUT_PROJECT_OPEN_SOURCE": t(locale, "about.project_open_source", ""),
        "ABOUT_PROJECT_VOLUNTEER": t(locale, "about.project_volunteer", ""),
        "ABOUT_PROJECT_WHAT": t(locale, "about.project_what", ""),
        "ABOUT_READ_MORE": t(locale, "about.read_more", ""),
        "ABOUT_SHOW_LESS": t(locale, "about.show_less", ""),
        "ABOUT_TITLE": t(locale, "about.title", ""),
        "COMMON_COMMUNITY_VERIFIED": t(locale, "common.community_verified", ""),
        "COMMON_DISCLAIMER": t(locale, "common.disclaimer", ""),
        "COMMON_MUNICIPAL_ESTIMATE": t(locale, "common.municipal_estimate", ""),
        "COMMON_NEEDS_VERIFICATION": t(locale, "common.needs_verification", ""),
        "COMMON_OFFICIAL": t(locale, "common.official", ""),
        "COMMON_PLACEHOLDER": t(locale, "common.placeholder", ""),
        "COMMON_PROVINCIAL_ESTIMATE": t(locale, "common.provincial_estimate", ""),
        "COMMON_STATUTORY": t(locale, "common.statutory", ""),
        "COMMON_UNOFFICIAL": t(locale, "common.unofficial", ""),
        "COMMON_VERIFIED": t(locale, "common.verified", ""),
        "EMERGENCY_FIRE": t(locale, "emergency.fire", ""),
        "EMERGENCY_LABEL": t(locale, "emergency.label", ""),
        "EMERGENCY_MDRRMO": t(locale, "emergency.mdrrmo", ""),
        "EMERGENCY_POLICE": t(locale, "emergency.police", ""),
        "GOVERNMENT_BARANGAY_COUNCILS_TITLE": t(locale, "government.barangay_councils_title", ""),
        "GOVERNMENT_CONTACT_COL_LANDLINE": t(locale, "government.contact_col_landline", ""),
        "GOVERNMENT_CONTACT_COL_MOBILE": t(locale, "government.contact_col_mobile", ""),
        "GOVERNMENT_CONTACT_COL_OFFICE": t(locale, "government.contact_col_office", ""),
        "GOVERNMENT_CONTACT_TITLE": t(locale, "government.contact_title", ""),
        "GOVERNMENT_DEPARTMENTS_TITLE": t(locale, "government.departments_title", ""),
        "GOVERNMENT_DEPT_COL_ACRONYM": t(locale, "government.dept_col_acronym", ""),
        "GOVERNMENT_DEPT_COL_LOCATION": t(locale, "government.dept_col_location", ""),
        "GOVERNMENT_DEPT_COL_OFFICE": t(locale, "government.dept_col_office", ""),
        "GOVERNMENT_EXECUTIVE_TITLE": t(locale, "government.executive_title", ""),
        "GOVERNMENT_EXTERNAL_TITLE": t(locale, "government.external_title", ""),
        "GOVERNMENT_LEGISLATIVE_TITLE": t(locale, "government.legislative_title", ""),
        "HERO_BROWSE_SERVICES": t(locale, "hero.browse_services", ""),
        "HERO_EYEBROW": t(locale, "hero.eyebrow", ""),
        "HERO_SEARCH_TITLE": t(locale, "hero.search_title", ""),
        "HERO_SEE_BUDGET": t(locale, "hero.see_budget", ""),
        "HERO_TITLE": t(locale, "hero.title", ""),
        "ACTION_HUB_SERVICES": t(locale, "action_hub.services", "Services"),
        "ACTION_HUB_BUDGET": t(locale, "action_hub.budget", "Budget"),
        "ACTION_HUB_LEGISLATION": t(locale, "action_hub.legislation", "Legislation"),
        "ACTION_HUB_HOTLINES": t(locale, "action_hub.hotlines", "Hotlines"),
        "HERO_LEDE": t(locale, "hero.subtitle", ""),
        "HERO_SEARCH_DESC": t(locale, "hero.search_desc", ""),
        "HERO_SEARCH_PLACEHOLDER": t(locale, "hero.search_placeholder", ""),
        "HERO_SEARCH_POPULAR": t(locale, "hero.search_popular", "Popular:"),
        ** _build_homepage_labels(locale),
        ** _build_statistics_labels(locale),
        ** _build_transparency_labels(locale),
        ** _build_dpwh_labels(locale),
        ** _build_search_labels(locale),
    }

def _build_homepage_labels(locale: dict) -> dict:
    return {
        "HOMEPAGE_AGRI_TITLE": t(locale, "homepage.agri_title", ""),
        "HOMEPAGE_BARANGAY_EYEBROW": t(locale, "homepage.barangay_eyebrow", ""),
        "HOMEPAGE_BARANGAY_TITLE": t(locale, "homepage.barangay_title", ""),
        "HOMEPAGE_CULTURAL_EYEBROW": t(locale, "homepage.cultural_eyebrow", ""),
        "HOMEPAGE_CULTURAL_TITLE": t(locale, "homepage.cultural_title", ""),
        "HOMEPAGE_EMERGENCY_BFP": t(locale, "homepage.emergency_bfp", ""),
        "HOMEPAGE_EMERGENCY_EYEBROW": t(locale, "homepage.emergency_eyebrow", ""),
        "HOMEPAGE_EMERGENCY_HOSPITAL": t(locale, "homepage.emergency_hospital", ""),
        "HOMEPAGE_EMERGENCY_MDRRMO_DESC": t(locale, "homepage.emergency_mdrmmo_desc", ""),
        "HOMEPAGE_EMERGENCY_PNP": t(locale, "homepage.emergency_pnp", ""),
        "HOMEPAGE_EMERGENCY_RHU": t(locale, "homepage.emergency_rhu", ""),
        "HOMEPAGE_EMERGENCY_TITLE": t(locale, "homepage.emergency_title", ""),
        "HOMEPAGE_EMERGENCY_WATER": t(locale, "homepage.emergency_water", ""),
        "HOMEPAGE_EXPLORE_EYEBROW": t(locale, "homepage.explore_eyebrow", ""),
        "HOMEPAGE_EXPLORE_TITLE": t(locale, "homepage.explore_title", ""),
        "HOMEPAGE_HISTORY_CTA": t(locale, "homepage.history_cta", ""),
        "HOMEPAGE_HISTORY_EYEBROW": t(locale, "homepage.history_eyebrow", ""),
        "HOMEPAGE_HISTORY_TITLE": t(locale, "homepage.history_title", ""),
        "HOMEPAGE_LEADERSHIP_CTA": t(locale, "homepage.leadership_cta", ""),
        "HOMEPAGE_LEADERSHIP_EYEBROW": t(locale, "homepage.leadership_eyebrow", ""),
        "HOMEPAGE_LEADERSHIP_TITLE": t(locale, "homepage.leadership_title", ""),
        "HOMEPAGE_MAP_TITLE": t(locale, "homepage.map_title", ""),
        "HOMEPAGE_MUNICIPALITY_AGRI": t(locale, "homepage.municipality_agri", ""),
        "HOMEPAGE_MUNICIPALITY_FOUNDED": t(locale, "homepage.municipality_founded", ""),
        "HOMEPAGE_MUNICIPALITY_REESTABLISHED": t(locale, "homepage.municipality_reestablished", ""),
        "HOMEPAGE_MUNICIPALITY_TITLE": t(locale, "homepage.municipality_title", ""),
        "HOMEPAGE_PLAZA_TITLE": t(locale, "homepage.plaza_title", ""),
        "HOMEPAGE_WEATHER_TITLE": t(locale, "homepage.weather_title", ""),
        "HOMEPAGE_MUNICIPALITY_EYEBROW": t(locale, "homepage.municipality_eyebrow", ""),
        "HOMEPAGE_MUNICIPALITY_DESC": t(locale, "homepage.municipality_desc", ""),
        "HOMEPAGE_FOUNDED_DESC": t(locale, "homepage.founded_desc", ""),
        "HOMEPAGE_REESTABLISHED_DESC": t(locale, "homepage.reestablished_desc", ""),
        "HOMEPAGE_AGRI_DESC_FULL": t(locale, "homepage.agri_desc_full", ""),
        "HOMEPAGE_HISTORY_SUBTITLE": t(locale, "homepage.history_subtitle", ""),
        "HOMEPAGE_MILESTONE1_ERA": t(locale, "homepage.milestone1_era", ""),
        "HOMEPAGE_MILESTONE1_TITLE": t(locale, "homepage.milestone1_title", ""),
        "HOMEPAGE_MILESTONE1_DESC": t(locale, "homepage.milestone1_desc", ""),
        "HOMEPAGE_MILESTONE2_ERA": t(locale, "homepage.milestone2_era", ""),
        "HOMEPAGE_MILESTONE2_TITLE": t(locale, "homepage.milestone2_title", ""),
        "HOMEPAGE_MILESTONE2_DESC": t(locale, "homepage.milestone2_desc", ""),
        "HOMEPAGE_MILESTONE3_ERA": t(locale, "homepage.milestone3_era", ""),
        "HOMEPAGE_MILESTONE3_TITLE": t(locale, "homepage.milestone3_title", ""),
        "HOMEPAGE_MILESTONE3_DESC": t(locale, "homepage.milestone3_desc", ""),
        "HOMEPAGE_MILESTONE4_ERA": t(locale, "homepage.milestone4_era", ""),
        "HOMEPAGE_MILESTONE4_TITLE": t(locale, "homepage.milestone4_title", ""),
        "HOMEPAGE_MILESTONE4_DESC": t(locale, "homepage.milestone4_desc", ""),
        "HOMEPAGE_BARANGAY_SUBTITLE": t(locale, "homepage.barangay_subtitle", ""),
        "HOMEPAGE_SOURCES_TITLE": t(locale, "homepage.sources_title", "Sources & Historical Notes"),
        "HOMEPAGE_SOURCES_DESC": t(locale, "homepage.sources_desc", ""),
        "HOMEPAGE_PANDAN_TITLE": t(locale, "homepage.pandan_title", "Pandan Festival"),
        "HOMEPAGE_PANDAN_DESC": t(locale, "homepage.pandan_desc", ""),
        "HOMEPAGE_PANDAN_CREDIT": t(locale, "homepage.pandan_credit", ""),
        "HOMEPAGE_PLAZA_DESC": t(locale, "homepage.plaza_desc", ""),
        "HOMEPAGE_PLAZA_CREDIT": t(locale, "homepage.plaza_credit", ""),
        "HOMEPAGE_AGRI_DESC": t(locale, "homepage.agri_desc", ""),
        "HOMEPAGE_AGRI_CREDIT": t(locale, "homepage.agri_credit", ""),
        "HOMEPAGE_MAYOR_NAME": t(locale, "homepage.mayor_name", ""),
        "HOMEPAGE_MAYOR_ROLE": t(locale, "homepage.mayor_role", "Municipal Mayor"),
        "HOMEPAGE_MAYOR_AFFIL": t(locale, "homepage.mayor_affil", ""),
        "HOMEPAGE_VICE_MAYOR_NAME": t(locale, "homepage.vice_mayor_name", ""),
        "HOMEPAGE_VICE_MAYOR_ROLE": t(locale, "homepage.vice_mayor_role", "Vice Mayor &middot; Presiding Officer"),
        "HOMEPAGE_VICE_MAYOR_AFFIL": t(locale, "homepage.vice_mayor_affil", "Independent (IND)"),
        "HOMEPAGE_LEADER_SOURCE": t(locale, "homepage.leader_source", "Source: Mapandan.gov.ph"),
        "HOMEPAGE_WEATHER_LOADING": t(locale, "homepage.weather_loading", "Loading weather data..."),
        "HOMEPAGE_WEATHER_CTA": t(locale, "homepage.weather_cta", "View PAGASA Advisories &rarr;"),
        "HOMEPAGE_MAP_CTA": t(locale, "homepage.map_cta", "Open in Google Maps &rarr;"),
        "HOMEPAGE_TRANSPARENCY_DESC": t(locale, "homepage.transparency_desc", ""),
        "HOMEPAGE_TRANSPARENCY_EYEBROW": t(locale, "homepage.transparency_eyebrow", ""),
        "HOMEPAGE_TRANSPARENCY_TITLE": t(locale, "homepage.transparency_title", ""),
        "STATS_BARANGAYS": t(locale, "stats.barangays", ""),
        "STATS_DENSITY": t(locale, "stats.density", ""),
        "STATS_HOUSEHOLDS": t(locale, "stats.households", ""),
        "STATS_LAND_AREA": t(locale, "stats.land_area", ""),
        "STATS_RESIDENTS": t(locale, "stats.residents", ""),
    }

def _build_statistics_labels(locale: dict) -> dict:
    return {
        "STATISTICS_AGRI_CROPS": t(locale, "statistics.agri_crops", ""),
        "STATISTICS_AGRI_IRRIGATED": t(locale, "statistics.agri_irrigated", ""),
        "STATISTICS_AGRI_TITLE": t(locale, "statistics.agri_title", ""),
        "STATISTICS_CHART_DOWNLOAD": t(locale, "statistics.chart_download", ""),
        "STATISTICS_CHART_POP_TREND": t(locale, "statistics.chart_pop_trend", ""),
        "STATISTICS_ECON_AGRI_EMP": t(locale, "statistics.econ_agri_emp", ""),
        "STATISTICS_ECON_DYNAMISM": t(locale, "statistics.econ_dynamism", ""),
        "STATISTICS_ECON_LABOR": t(locale, "statistics.econ_labor", ""),
        "STATISTICS_ECON_POVERTY": t(locale, "statistics.econ_poverty", ""),
        "STATISTICS_ECON_TITLE": t(locale, "statistics.econ_title", ""),
        "STATISTICS_FISCAL_BALANCE_2025": t(locale, "statistics.fiscal_balance_2025", ""),
        "STATISTICS_FISCAL_BLGF": t(locale, "statistics.fiscal_blgf", ""),
        "STATISTICS_FISCAL_BLGF_TITLE": t(locale, "statistics.fiscal_blgf_title", ""),
        "STATISTICS_FISCAL_EXP_2025": t(locale, "statistics.fiscal_exp_2025", ""),
        "STATISTICS_FISCAL_REV_2025": t(locale, "statistics.fiscal_rev_2025", ""),
        "STATISTICS_FISCAL_TITLE": t(locale, "statistics.fiscal_title", ""),
        "STATISTICS_GROWTH_TITLE": t(locale, "statistics.growth_title", ""),
        "STATISTICS_LAND_BARANGAYS": t(locale, "statistics.land_barangays", ""),
        "STATISTICS_LAND_EYEBROW": t(locale, "statistics.land_eyebrow", ""),
        "STATISTICS_LAND_TITLE": t(locale, "statistics.land_title", ""),
        "STATISTICS_LAND_TOTAL": t(locale, "statistics.land_total", ""),
        "STATISTICS_LAND_URBAN_RURAL": t(locale, "statistics.land_urban_rural", ""),
        "STATISTICS_POP_DENSITY": t(locale, "statistics.pop_density", ""),
        "STATISTICS_POP_HOUSEHOLDS": t(locale, "statistics.pop_households", ""),
        "STATISTICS_POP_TITLE": t(locale, "statistics.pop_title", ""),
        "STATISTICS_POP_TOTAL": t(locale, "statistics.pop_total", ""),
        "STATISTICS_TITLE": t(locale, "statistics.title", ""),
        "STATISTICS_TRENDS_TITLE": t(locale, "statistics.trends_title", ""),
    }

def _build_transparency_labels(locale: dict) -> dict:
    return {
        "DPWH_EYEBROW": t(locale, "transparency.infrastructure_eyebrow", "DPWH &middot; Infrastructure"),
        "DPWH_TITLE": t(locale, "transparency.infrastructure_title", "Infrastructure Projects"),
        "DPWH_LEDE": t(locale, "transparency.infrastructure_lede", "DPWH contracts, road and flood-control projects, school buildings, and health facilities in Mapandan."),
        "TRANSPARENCY_APPROPRIATIONS_EYEBROW": t(locale, "transparency.appropriations_eyebrow", ""),
        "TRANSPARENCY_APPROPRIATIONS_TITLE": t(locale, "transparency.appropriations_title", ""),
        "TRANSPARENCY_AUDIT_TITLE": t(locale, "transparency.audit_title", ""),
        "TRANSPARENCY_BALANCE_ASSETS": t(locale, "transparency.balance_assets", ""),
        "TRANSPARENCY_BALANCE_EYEBROW": t(locale, "transparency.balance_eyebrow", ""),
        "TRANSPARENCY_BALANCE_LIABILITIES": t(locale, "transparency.balance_liabilities", ""),
        "TRANSPARENCY_BALANCE_NET": t(locale, "transparency.balance_net", ""),
        "TRANSPARENCY_BALANCE_TITLE": t(locale, "transparency.balance_title", ""),
        "TRANSPARENCY_BUDGET_2026": t(locale, "transparency.budget_2026", ""),
        "TRANSPARENCY_BUDGET_TREND_EYEBROW": t(locale, "transparency.budget_trend_eyebrow", ""),
        "TRANSPARENCY_CAPEX_EYEBROW": t(locale, "transparency.capex_eyebrow", ""),
        "TRANSPARENCY_CAPEX_TITLE": t(locale, "transparency.capex_title", ""),
        "TRANSPARENCY_COMPLIANCE_COA": t(locale, "transparency.compliance_coa", ""),
        "TRANSPARENCY_COMPLIANCE_FDP": t(locale, "transparency.compliance_fdp", ""),
        "TRANSPARENCY_COMPLIANCE_SGLG": t(locale, "transparency.compliance_sglg", ""),
        "TRANSPARENCY_COMPLIANCE_TITLE": t(locale, "transparency.compliance_title", ""),
        "TRANSPARENCY_CREDIT_EYEBROW": t(locale, "transparency.credit_eyebrow", ""),
        "TRANSPARENCY_CREDIT_TITLE": t(locale, "transparency.credit_title", ""),
        "TRANSPARENCY_EXPENDITURE_2025": t(locale, "transparency.expenditure_2025", ""),
        "TRANSPARENCY_EXTERNAL_EYEBROW": t(locale, "transparency.external_eyebrow", ""),
        "TRANSPARENCY_EXTERNAL_TITLE": t(locale, "transparency.external_title", ""),
        "TRANSPARENCY_FISCAL_DEV_FUND": t(locale, "transparency.fiscal_dev_fund", ""),
        "TRANSPARENCY_FISCAL_LDRRMF": t(locale, "transparency.fiscal_ldrrmf", ""),
        "TRANSPARENCY_FISCAL_NTA": t(locale, "transparency.fiscal_nta", ""),
        "TRANSPARENCY_FISCAL_PS_CAP": t(locale, "transparency.fiscal_ps_cap", ""),
        "TRANSPARENCY_FISCAL_SEF": t(locale, "transparency.fiscal_sef", ""),
        "TRANSPARENCY_FISCAL_SNAPSHOT_TITLE": t(locale, "transparency.fiscal_snapshot_title", ""),
        "TRANSPARENCY_FISCAL_STRUCTURE_EYEBROW": t(locale, "transparency.fiscal_structure_eyebrow", ""),
        "TRANSPARENCY_FISCAL_STRUCTURE_TITLE": t(locale, "transparency.fiscal_structure_title", ""),
        "TRANSPARENCY_HISTORICAL_EYEBROW": t(locale, "transparency.historical_eyebrow", ""),
        "TRANSPARENCY_HISTORICAL_INC_OPS": t(locale, "transparency.historical_inc_ops", ""),
        "TRANSPARENCY_HISTORICAL_MOOE": t(locale, "transparency.historical_mooe", ""),
        "TRANSPARENCY_HISTORICAL_TAX_REV": t(locale, "transparency.historical_tax_rev", ""),
        "TRANSPARENCY_HISTORICAL_TITLE": t(locale, "transparency.historical_title", ""),
        "TRANSPARENCY_HISTORICAL_TOTAL_EQUITY": t(locale, "transparency.historical_total_equity", ""),
        "TRANSPARENCY_HISTORICAL_TOTAL_OP_EXP": t(locale, "transparency.historical_total_op_exp", ""),
        "TRANSPARENCY_HISTORICAL_TOTAL_OP_INC": t(locale, "transparency.historical_total_op_inc", ""),
        "TRANSPARENCY_LATEST_COA_NOTE": t(locale, "transparency.latest_coa_note", ""),
        "TRANSPARENCY_PROCUREMENT_EYEBROW": t(locale, "transparency.procurement_eyebrow", ""),
        "TRANSPARENCY_PROCUREMENT_TITLE": t(locale, "transparency.procurement_title", ""),
        "TRANSPARENCY_REVENUE_2025": t(locale, "transparency.revenue_2025", ""),
        "TRANSPARENCY_REVENUE_TITLE": t(locale, "transparency.revenue_title", ""),
        "TRANSPARENCY_COA_PROJECTS_EYEBROW": t(locale, "transparency.coa_projects_eyebrow", ""),
        "TRANSPARENCY_COA_PROJECTS_TITLE": t(locale, "transparency.coa_projects_title", ""),
        "TRANSPARENCY_COA_PROJECTS_DESC": t(locale, "transparency.coa_projects_desc", ""),
        "TRANSPARENCY_COA_PROJECT_NAME": t(locale, "transparency.coa_project_name", ""),
        "TRANSPARENCY_COA_PROJECT_COST": t(locale, "transparency.coa_project_cost", ""),
        "TRANSPARENCY_COA_PROJECT_YEAR": t(locale, "transparency.coa_project_year", ""),
        "TRANSPARENCY_COA_PROJECT_CATEGORY": t(locale, "transparency.coa_project_category", ""),
        "TRANSPARENCY_COA_PROJECT_STATUS": t(locale, "transparency.coa_project_status", ""),
        "TRANSPARENCY_REFORM_EYEBROW": t(locale, "transparency.reform_eyebrow", ""),
        "TRANSPARENCY_REFORM_TITLE": t(locale, "transparency.reform_title", ""),
        "TRANSPARENCY_REFORM_DESC": t(locale, "transparency.reform_desc", ""),
        "TRANSPARENCY_DISALLOWANCES_EYEBROW": t(locale, "transparency.disallowances_eyebrow", ""),
        "TRANSPARENCY_DISALLOWANCES_TITLE": t(locale, "transparency.disallowances_title", ""),
        "TRANSPARENCY_DISALLOWANCES_DESC": t(locale, "transparency.disallowances_desc", ""),
        "TRANSPARENCY_SOCIAL_AGRI": t(locale, "transparency.social_agri", ""),
        "TRANSPARENCY_SOCIAL_EYEBROW": t(locale, "transparency.social_eyebrow", ""),
        "TRANSPARENCY_SOCIAL_TITLE": t(locale, "transparency.social_title", ""),
        "TRANSPARENCY_TITLE": t(locale, "transparency.title", ""),
        "AUDIT_OPINION_EYEBROW": t(locale, "transparency.audit_opinion_eyebrow", ""),
        "AUDIT_OPINION_TITLE": t(locale, "transparency.audit_opinion_title", ""),
        "AUDIT_OPINION_DESC": t(locale, "transparency.audit_opinion_desc", ""),
        "AUDIT_OPINION_CHART_TITLE": t(locale, "transparency.audit_opinion_chart_title", ""),
        "FINANCIAL_PERF_EYEBROW": t(locale, "transparency.financial_perf_eyebrow", ""),
        "FINANCIAL_PERF_TITLE": t(locale, "transparency.financial_perf_title", ""),
        "FINANCIAL_PERF_DESC": t(locale, "transparency.financial_perf_desc", ""),
        "FINANCIAL_PERF_ASSETS_TITLE": t(locale, "transparency.financial_perf_assets_title", ""),
        "FINANCIAL_PERF_INCOME_TITLE": t(locale, "transparency.financial_perf_income_title", ""),
        "FINANCIAL_PERF_REVENUE_TITLE": t(locale, "transparency.financial_perf_revenue_title", ""),
        "FINANCIAL_PERF_TABLE_TITLE": t(locale, "transparency.financial_perf_table_title", ""),
        "AUDIT_FINDINGS_EYEBROW": t(locale, "transparency.audit_findings_eyebrow", ""),
        "AUDIT_FINDINGS_TITLE": t(locale, "transparency.audit_findings_title", ""),
        "AUDIT_FINDINGS_DESC": t(locale, "transparency.audit_findings_desc", ""),
        "IMPL_RATE_EYEBROW": t(locale, "transparency.impl_rate_eyebrow", ""),
        "IMPL_RATE_TITLE": t(locale, "transparency.impl_rate_title", ""),
        "IMPL_RATE_DESC": t(locale, "transparency.impl_rate_desc", ""),
        "IMPL_RATE_CHART_TITLE": t(locale, "transparency.impl_rate_chart_title", ""),
        "IMPL_RATE_TABLE_TITLE": t(locale, "transparency.impl_rate_table_title", ""),
        "TRANSPARENCY_VIEW_TABLE": t(locale, "transparency.dash_view_table", "View full tables"),
        "TRANSPARENCY_CLOSE": t(locale, "transparency.dash_close", "Close"),
    }

def _build_search_labels(locale: dict) -> dict:
    return {
        "SEARCH_TITLE": t(locale, "search_page.title", ""),
        "SEARCH_SUBTITLE": t(locale, "search_page.subtitle", ""),
        "SEARCH_BROWSE_EYEBROW": t(locale, "search_page.browse_eyebrow", ""),
        "SEARCH_BROWSE_TITLE": t(locale, "search_page.browse_title", ""),
        "SEARCH_POPULAR_TITLE": t(locale, "search_page.popular_title", ""),
        "SEARCH_POPULAR_BIZ": t(locale, "search_page.popular_biz", ""),
        "SEARCH_POPULAR_CIVIL": t(locale, "search_page.popular_civil", ""),
        "SEARCH_POPULAR_HEALTH": t(locale, "search_page.popular_health", ""),
        "SEARCH_POPULAR_WELFARE": t(locale, "search_page.popular_welfare", ""),
        "REPORT_CHOOSE_TITLE": t(locale, "report_hub.choose_title", ""),
        "REPORT_ERROR": t(locale, "report_hub.report_error", ""),
        "REPORT_SUBMIT_INFO": t(locale, "report_hub.submit_info", ""),
        "REPORT_SUGGEST_FEATURE": t(locale, "report_hub.suggest_feature", ""),
        "REPORT_NEXT_TITLE": t(locale, "report_hub.next_title", ""),
        "REPORT_VERIFICATION_TITLE": t(locale, "report_hub.verification_title", ""),
    }
